### ISSUE TITLE
Stardist plugin startup_abstract error

### ISSUE THREAD

**Issue by pr4deepr** [mpicbg-csbd/stardist-imagej#3]
HI 
   Apologies for double posting, but I have posted this issue on the [ImageJ forum](https://forum.image.sc/t/stardist-plugin-startup-abstract-method-error/35123). 
Thought I'll cross post here in case you don't visit the forum often and for future users. 
 have been getting an error when I try to open Stardist plugin. It was working a few days ago and am not sure if its because of an update.
Regardless of the type of image open, when I click StarDist 2D, I get the following error:
```

Tue Mar 17 12:11:40 AEDT 2020] [ERROR] [] Module threw error
java.lang.AbstractMethodError: Method net/imglib2/img/VirtualStackAdapter$ImagePlusLoader$$Lambda$96.extract(Ljava/lang/Object;)Ljava/lang/Object; is abstract
	at net.imglib2.img.VirtualStackAdapter$ImagePlusLoader$$Lambda$96/2095461678.extract(Unknown Source)
	at net.imglib2.cache.ref.SoftRefLoaderRemoverCache$Entry.setValue(SoftRefLoaderRemoverCache.java:78)
	at net.imglib2.cache.ref.SoftRefLoaderRemoverCache.get(SoftRefLoaderRemoverCache.java:130)
	at net.imglib2.cache.util.LoaderRemoverCacheAsRemoverCacheAdapter.get(LoaderRemoverCacheAsRemoverCacheAdapter.java:45)
	at net.imglib2.cache.util.RemoverCacheAsCacheAdapter.get(RemoverCacheAsCacheAdapter.java:43)
	at net.imglib2.img.VirtualStackAdapter$ImagePlusLoader.get(VirtualStackAdapter.java:178)
	at net.imglib2.img.VirtualStackAdapter$ImagePlusLoader.get(VirtualStackAdapter.java:158)
	at net.imglib2.img.planar.PlanarImg.update(PlanarImg.java:118)
	at net.imglib2.img.planar.PlanarImg.update(PlanarImg.java:66)
	at net.imglib2.type.numeric.integer.GenericShortType.updateContainer(GenericShortType.java:100)
	at net.imglib2.img.planar.PlanarCursor.reset(PlanarCursor.java:162)
	at net.imglib2.img.planar.PlanarCursor.<init>(PlanarCursor.java:90)
	at net.imglib2.img.planar.PlanarCursor2D.<init>(PlanarCursor2D.java:50)
	at net.imglib2.img.planar.PlanarImg.cursor(PlanarImg.java:217)
	at net.imglib2.img.planar.PlanarImg.cursor(PlanarImg.java:66)
	at net.imglib2.img.AbstractImg.firstElement(AbstractImg.java:81)
	at net.imagej.ImgPlus.firstElement(ImgPlus.java:276)
	at net.imagej.DefaultDataset.getType(DefaultDataset.java:220)
	at net.imagej.DefaultDataset.isSigned(DefaultDataset.java:225)
	at net.imagej.DefaultDataset.mergedColorCompatible(DefaultDataset.java:704)
	at net.imagej.DefaultDataset.<init>(DefaultDataset.java:101)
	at net.imagej.DefaultDatasetService.create(DefaultDatasetService.java:200)
	at net.imagej.legacy.translate.DisplayCreator.makeDataset(DisplayCreator.java:139)
	at net.imagej.legacy.translate.DisplayCreator.getDataset(DisplayCreator.java:101)
	at net.imagej.legacy.translate.DisplayCreator.makeDisplay(DisplayCreator.java:179)
	at net.imagej.legacy.translate.DisplayCreator.createDisplay(DisplayCreator.java:93)
	at net.imagej.legacy.translate.ImageTranslator.createDisplay(ImageTranslator.java:64)
	at net.imagej.legacy.LegacyImageMap.registerLegacyImage(LegacyImageMap.java:288)
	at net.imagej.legacy.display.LegacyImageDisplayService.getActiveImageDisplay(LegacyImageDisplayService.java:117)
	at net.imagej.legacy.display.LegacyImageDisplayService.getActiveDataset(LegacyImageDisplayService.java:128)
	at net.imagej.display.process.ActiveDatasetPreprocessor.getValue(ActiveDatasetPreprocessor.java:72)
	at net.imagej.display.process.ActiveDatasetPreprocessor.getValue(ActiveDatasetPreprocessor.java:56)
	at net.imagej.display.process.SingleInputPreprocessor.process(SingleInputPreprocessor.java:85)
	at org.scijava.module.ModuleRunner.preProcess(ModuleRunner.java:105)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:157)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Not sure what is going on.
When I try starting the plugin again, I get the window, but in the Input image box, I get:
 
![image](https://user-images.githubusercontent.com/13831458/77002958-900aaa00-69b0-11ea-98c3-e029c7a0b5c2.png)

BTW, I just used a random sample image to demonstrate what the input image box looks like. It shows image name, bit depth, resolution..
If I click Ok, I get an empty dialog box with just the OK button. After clicking it, nothing happens.

Thanks
Pradeep

**Comment by uschmidt83** [comment]
Hi Pradeep,

sorry for not replying sooner, but I was away from my computer last week.

> Thought I'll cross post here in case you don't visit the forum often and for future users.

I'm subscribed to the `stardist` tag at the forum to not miss StarDist-related posts.

I'm closing this issue since it seems to be [resolved](https://forum.image.sc/t/stardist-plugin-startup-abstract-method-error/35123/6).

Best,
Uwe
